"""change password_hash column to password

Revision ID: 040c1d8437ec
Revises: 
Create Date: 2024-04-23 00:52:06.544935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '040c1d8437ec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=128), nullable=False))
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
        batch_op.drop_column('password')

    # ### end Alembic commands ###
